CREATE DATABASE IF NOT EXISTS Ejercicio_dml_1;

USE Ejercicio_dml_1;

CREATE TABLE PROVEEDORES
(NUMERO INT NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
DOMICILIO VARCHAR(15) NOT NULL,
LOCALIDAD VARCHAR(12),
PRIMARY KEY (NUMERO));

CREATE TABLE PRODUCTOS
(PNRO INT NOT NULL,
PNOMBRE VARCHAR(20) NOT NULL,
PRECIO INT NOT NULL,
TAMAÑO VARCHAR(20),
LOCALIDAD VARCHAR(12) NOT NULL,
PRIMARY KEY (PNRO));

CREATE TABLE PROV_PROD
(NUMERO INT NOT NULL,
PNRO INT NOT NULL,
CANTIDAD INT NOT NULL,
PRIMARY KEY (NUMERO, PNRO),
FOREIGN KEY (NUMERO) REFERENCES PROVEEDORES (NUMERO),
FOREIGN KEY (PNRO) REFERENCES PRODUCTOS (PNRO));

INSERT INTO proveedores (NUMERO, NOMBRE, DOMICILIO, LOCALIDAD)
VALUES (101 ,"Gómez", "Nazca 920" ,"Capital"),
(102 ,"Pérez" ,"Argerich 1030" ,"Capital"),
(103 ,"Vázquez" ,"Sarmiento 450" ,"Ramos Mejía"),
(104 ,"López" ,"Alsina 720" ,"Avellaneda");

INSERT INTO productos (PNRO, PNOMBRE, PRECIO, TAMAÑO, LOCALIDAD)
VALUES (001, "Talco", 500, "Chico", "Capital"),
(002, "Cepillo", 2500, "Grande", "Avellaneda"),
(003, "Jabon", 2500, "Mediano", "Wilde");

INSERT INTO prov_prod (NUMERO, PNRO, CANTIDAD)
VALUES #(101 , 001, 300),
#(101 , 002, 200),
(102, 003, 100),
(103 , 001, 300);

UPDATE productos
SET TAMAÑO = 'Chico'
WHERE TAMAÑO = 'Mediano';